services:
  - type: web
    name: streetsaver
    env: static
    buildCommand: chmod +x ./build.sh && ./build.sh
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
